name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    defaults:
      run:
        working-directory: Source

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore
      run: dotnet restore PayloadPanda.sln

    - name: Build
      run: dotnet build PayloadPanda.sln --configuration ${{ matrix.configuration }} --no-restore

    - name: Publish
      if: matrix.configuration == 'Release'
      run: dotnet publish PayloadPanda.csproj --configuration Release --output publish --no-restore

    - name: Upload artifact
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: PayloadPanda-win-x64
        path: Source/publish
